### PR TITLE
162 create a config file with params

### LINKED ISSUE #162: Create a config file with params'

### LINKED ISSUE #166: Jittering not working
I'm hitting this error during the jittering stage:

```
  Last error: Cannot open "/tmp/Rtmp6KYu5S/od_jittered.geojson"; The file doesn't seem to exist.
```

### PR DESCRIPTION
**Pull request by atumscott**
- Add json file, fix #162
- Update Rust crate and document, close #166

### CODE REVIEW

**Comment by Robinlovelace** [comment]
image

That's the current build status according to {targets}.

Fun one for you @temospena, I know you've started using it, is this getting too complicated?! Also loving targets, for now...

**Comment by Robinlovelace** [comment]
Really cool thing about this workflow: after changing the parameters.json file in the commit above it knows to rebuild most of the targets:

image

**Comment by Robinlovelace** [comment]
Update here, 18k routes in action!

image

**Comment by Robinlovelace** [comment]
CycleStreets batch routing chugging away nicely, topping out at ~20 routes per second, given that we get ~3 routes per second in non batch mode that's almost a 10x speed-up so heads-up on that @mvl22 also, still think we would benefit by sending batches in parallel rather than in series, see #123 for that and if you're up for taking a look at that issue anyone that would be amazing.

image

**Comment by Robinlovelace** [comment]
Plan: merge this by end of play today if possible..

File: R/get_area.R [hunk 1]
```diff
@@ -0,0 +1,6 @@
+# Aim: get generate a test area
+# location_name = "Forth bridge"
+get_area = function(location_name = "Forth bridge", d = 20) {
+  location_sf = tmaptools::geocode_OSM(location_name, as.sf = TRUE)
+  zonebuilder::zb_doughnut(x = location_sf, n_circles = 1, distance = d)
```
Comment (joeytalbot) [inline R/get_area.R:5]: Very nice

**Review by joeytalbot — APPROVED** [review]
This looks like it reduces the amount of code in _targets.R which will be helpful

**Comment by Robinlovelace** [comment]
Thanks for reviewing + merging this PR Joey :tada:
